<?php  

$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Zend Framework CD Application');

echo $this->doctype();

?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<?= $this->headMeta(); ?>
	<?= $this->headTitle(); ?>
	<?= $this->headLink()->prependStylesheet($this->baseUrl().'/bootstrap-4.0.0/css/site.css'); ?>
	<?= $this->headLink()->prependStylesheet($this->baseUrl().'/bootstrap-4.0.0/css/bootstrap.min.css');?>
</head>
<body>
	<div id="content">
		<h1 style="text-align: center; margin-top: 60px; font-weight: bold;"><?= $this->escape($this->title); ?></h1>
		<!-- $this->layout()->content; -->

	</div>
</body>
</html>







<?php echo $this->layout()->content; ?>